### PR TITLE
Add input component

### PR DESCRIPTION
**Pull request by kavin25**
Screenshot 2021-10-03 at 12 14 21 PM

### CODE REVIEW

**Comment by adibemohamed** [comment]
Check the new version, and update your changes, and PR again.

**Comment by kavin25** [comment]
@adibemohamed merged the conflicts

**Review by adibemohamed — COMMENTED** [review]
done

**Comment by adibemohamed** [comment]
try to make your input style better

**Comment by kavin25** [comment]
@adibemohamed Oh wait, it looks like something got messed up during the merge conflict. Let me check

**Comment by adibemohamed** [comment]
Yes, I just figure out you're missing the Input component. Please follow the instructions README.md
https://github.com/adibemohamed/ready-tailwindcss#readme

**Pull request merged**
